// flow-typed signature: 3a14e3cb497bdcf7a364f8232c34d87d
// flow-typed version: <<STUB>>/apollo-server_v^0.3.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server/dist/core/runQuery' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/core/runQuery.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/apolloOptions' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/connectApollo' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/connectApollo.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/expressApollo' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/expressApollo.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/hapiApollo' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/hapiApollo.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/integrations.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/koaApollo' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/integrations/koaApollo.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/modules/operationStore' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/modules/operationStore.test' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/modules/renderGraphiQL' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server/dist/core/runQuery.js' {
  declare module.exports: $Exports<'apollo-server/dist/core/runQuery'>;
}
declare module 'apollo-server/dist/core/runQuery.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/core/runQuery.test'>;
}
declare module 'apollo-server/dist/index.js' {
  declare module.exports: $Exports<'apollo-server/dist/index'>;
}
declare module 'apollo-server/dist/integrations/apolloOptions.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/apolloOptions'>;
}
declare module 'apollo-server/dist/integrations/connectApollo.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/connectApollo'>;
}
declare module 'apollo-server/dist/integrations/connectApollo.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/connectApollo.test'>;
}
declare module 'apollo-server/dist/integrations/expressApollo.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/expressApollo'>;
}
declare module 'apollo-server/dist/integrations/expressApollo.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/expressApollo.test'>;
}
declare module 'apollo-server/dist/integrations/hapiApollo.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/hapiApollo'>;
}
declare module 'apollo-server/dist/integrations/hapiApollo.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/hapiApollo.test'>;
}
declare module 'apollo-server/dist/integrations/integrations.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/integrations.test'>;
}
declare module 'apollo-server/dist/integrations/koaApollo.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/koaApollo'>;
}
declare module 'apollo-server/dist/integrations/koaApollo.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/integrations/koaApollo.test'>;
}
declare module 'apollo-server/dist/modules/operationStore.js' {
  declare module.exports: $Exports<'apollo-server/dist/modules/operationStore'>;
}
declare module 'apollo-server/dist/modules/operationStore.test.js' {
  declare module.exports: $Exports<'apollo-server/dist/modules/operationStore.test'>;
}
declare module 'apollo-server/dist/modules/renderGraphiQL.js' {
  declare module.exports: $Exports<'apollo-server/dist/modules/renderGraphiQL'>;
}
